name: Latest Youtube Videos Worflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from Youtube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: guatamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "http://www.youtube.com/feeds/videos.xml?channel_id=UCDCHcqyeQgJ-jVSd6VJkbCw"